import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Sidebar from "./(landing)/components/Sidebar";
import QueryClientProviderContext from "./query-client-provider";
import Header from "./(landing)/components/Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="flex">
					<Sidebar />
					<div className="flex-1">
						<Header />
						<QueryClientProviderContext>{children}</QueryClientProviderContext>
					</div>
				</div>

				<Toaster />
			</body>
		</html>
	);
}
